# Generated by Django 3.1.12 on 2026-10-05 02:29

from django.db import migrations, models
import djongo.models.fields
import pagos_facturacion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('cedula_cliente', models.CharField(max_length=20)),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('placa_vehiculo', models.CharField(max_length=10)),
                ('subtotal', models.FloatField()),
                ('impuesto_iva', models.FloatField()),
                ('total', models.FloatField()),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='emitida', max_length=20)),
                ('pagos', djongo.models.fields.ArrayField(blank=True, model_container=pagos_facturacion.models.DetallePago)),
            ],
            options={
                'db_table': 'facturas',
            },
        ),
    ]
