# Generated by Django 3.1.12 on 2026-10-05 02:29

from django.db import migrations, models
import djongo.models.fields
import gestion_usuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('contrasena', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('es_administrador', models.BooleanField(default=False)),
                ('es_superusuario', models.BooleanField(default=False)),
                ('esta_activo', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('rol', djongo.models.fields.EmbeddedField(blank=True, model_container=gestion_usuarios.models.Rol, null=True)),
                ('auditoria', djongo.models.fields.ArrayField(blank=True, model_container=gestion_usuarios.models.AuditoriaItem)),
                ('metas', djongo.models.fields.ArrayField(blank=True, model_container=gestion_usuarios.models.MetaVentas)),
                ('notificaciones', djongo.models.fields.ArrayField(blank=True, model_container=gestion_usuarios.models.Notificacion)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
