# Generated by Django 3.1.12 on 2026-10-05 02:29

from django.db import migrations, models
import djongo.models.fields
import ventas_cotizaciones.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('creado_por', djongo.models.fields.EmbeddedField(model_container=ventas_cotizaciones.models.CreadoPor)),
                ('condiciones', djongo.models.fields.ArrayField(blank=True, model_container=ventas_cotizaciones.models.Condicion)),
                ('descuentos', djongo.models.fields.ArrayField(blank=True, model_container=ventas_cotizaciones.models.Descuento)),
                ('notas_adicionales', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'plantillasCotizacion',
            },
        ),
    ]
