# Generated by Django 3.1.12 on 2026-10-05 02:29

import clientes_vehiculos.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('cotizaciones', djongo.models.fields.ArrayField(blank=True, model_container=clientes_vehiculos.models.Cotizacion)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=30)),
                ('placa', models.CharField(max_length=10)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('kilometraje', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], default='disponible', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('propietarios_anteriores', djongo.models.fields.ArrayField(blank=True, model_container=clientes_vehiculos.models.PropietarioAnterior)),
                ('mantenimientos', djongo.models.fields.ArrayField(blank=True, model_container=clientes_vehiculos.models.Mantenimiento)),
            ],
            options={
                'db_table': 'vehiculos',
            },
        ),
    ]
